name: app_chat_proxy
description: "Self project for practice"
publish_to: "Firebase App Distribute"
version: 1.0.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

assets:
  - .env
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  auto_route: ^7.8.4
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  logger: ^2.0.2+1
  firebase_core: ^2.25.4
  firebase_analytics: ^10.8.6
  dio: ^5.4.1
  meta: ^1.10.0
  connectivity: ^3.0.6
  gap: ^3.0.1
  flutter_markdown: ^0.6.20
  flutter_highlighter: ^0.1.1
  flutter_highlight: ^0.7.0
  lite_rolling_switch: ^1.0.1
  flutter_native_splash: ^2.3.10
  package_info_plus: ^5.0.1
  flutter_animate: ^4.5.0
  sentry_flutter: ^7.16.1
  flex_color_scheme: ^7.3.1
  onesignal_flutter: ^5.1.0
  uni_links: ^0.5.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  generate: true
