name: app_chat_proxy
description: "Self project for practice"
publish_to: "Firebase App Distribute"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  auto_route: ^7.8.4
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  logger: ^2.0.2+1
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  generate: true